### ISSUE TITLE
NotFoundError: No type found for query when connecting over gRPC

### ISSUE THREAD

**Issue by RafalSkolasinski** [google/ml-metadata#79]
Following suggestion from https://github.com/google/ml-metadata/issues/76 I tried to explore k8s deployment similar to the one done in Kubeflow project.

Basing on these manifests https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/base/metadata I created a single deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc-deployment
  namespace: mlmd
  labels:
    component: metadata-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-grpc-server
  template:
    metadata:
      labels:
        component: metadata-grpc-server
    spec:
      containers:
      - name: container
        image: gcr.io/tfx-oss-public/ml_metadata_store_server:0.25.0
        command: ["/bin/metadata_store_server"]
        args: ["--grpc_port=8080",
               "--enable_database_upgrade=true"
               ]
        ports:
        - name: grpc-api
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
```
and service
```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: metadata
  name: metadata-grpc-service
  namespace: mlmd
spec:
  selector:
    component: metadata-grpc-server
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    name: grpc-api
```

In order to communicate with k8s-deployed microservice I forwarded its port with
```bash
kubectl port-forward -n mlmd svc/metadata-grpc-service 8080:8080
```

I also found these helper files in Kubeflow project https://github.com/kubeflow/pipelines/blob/master/backend/metadata_writer/src/metadata_helpers.py that provides useful level of abstraction. 

I first however tried code snippets from [mlmd documentatio](https://www.tensorflow.org/tfx/guide/mlmd#use_mlmd_with_a_remote_grpc_server) and noticed that both created artifacts  gets same `type_id: 1`. There is also nothing appearing in the pod's logs. 

Then inspired by Kubeflow metadata helpers I did
```python
from ml_metadata.proto import metadata_store_pb2
from ml_metadata.metadata_store import metadata_store

def connect_to_mlmd(metadata_service_host, metadata_service_port) -> metadata_store.MetadataStore:

    mlmd_connection_config = metadata_store_pb2.MetadataStoreClientConfig(
        host=metadata_service_host,
        port=metadata_service_port,
    )

    # Checking the connection to the Metadata store.
    for _ in range(100):
        try:
            mlmd_store = metadata_store.MetadataStore(mlmd_connection_config)
            # All get requests fail when the DB is empty, so we have to use a put request.
            # TODO: Replace with _ = mlmd_store.get_context_types() when https://github.com/google/ml-metadata/issues/28 is fixed
            _ = mlmd_store.put_execution_type(
                metadata_store_pb2.ExecutionType(
                    name="DummyExecutionType",
                )
            )
            return mlmd_store
        except Exception as e:
            print('Failed to access the Metadata store. Exception: "{}"'.format(str(e)), file=sys.stderr)
            sys.stderr.flush()
            sleep(1)

    raise RuntimeError('Could not connect to the Metadata store.')


def get_or_create_artifact_type(store, type_name, properties: dict = None) -> metadata_store_pb2.ArtifactType:
    try:
        artifact_type = store.get_artifact_type(type_name=type_name)
        return artifact_type
    except:
        artifact_type = metadata_store_pb2.ArtifactType(
            name=type_name,
            properties=properties,
        )
        artifact_type.id = store.put_artifact_type(artifact_type) # Returns ID
        return artifact_type


mlmd = connect_to_mlmd("localhost", 8080)    

artifact_type = get_or_create_artifact_type(
    mlmd, 
    type_name="MyArtifactType",
)

print(artifact_type)
```

which outputs
```
id: 1
name: "MyArtifactType"
```
with
```
2020-11-17 12:06:30.157710: W ml_metadata/metadata_store/rdbms_metadata_access_object.cc:588] No property is defined for the Type
2020-11-17 12:06:31.432750: W ml_metadata/metadata_store/metadata_store_service_impl.cc:79] GetArtifactType failed: No type found for query: MyArtifactType
2020-11-17 12:06:31.489764: W ml_metadata/metadata_store/rdbms_metadata_access_object.cc:588] No property is defined for the Type
```
being logged in the Pod.

However, trying 
```python
mlmd.get_artifact_type(type_name="MyArtifactType")
```
leads to
```python
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py in _call_method(self, method_name, request, response)
    174       try:
--> 175         response.CopyFrom(grpc_method(request, timeout=self._grpc_timeout_sec))
    176       except grpc.RpcError as e:

~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    922                                       wait_for_ready, compression)
--> 923         return _end_unary_response_blocking(state, call, False, None)
    924 

~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    825     else:
--> 826         raise _InactiveRpcError(state)
    827 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "No type found for query: MyArtifactType"
	debug_error_string = "{"created":"@1605614795.789362714","description":"Error received from peer ipv6:[::1]:8080","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"No type found for query: MyArtifactType","grpc_status":5}"
>

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-29-f3d6193a4029> in <module>
----> 1 mlmd.get_artifact_type(type_name="MyArtifactType")

~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py in get_artifact_type(self, type_name)
    629     response = metadata_store_service_pb2.GetArtifactTypeResponse()
    630 
--> 631     self._call('GetArtifactType', request, response)
    632     return response.artifact_type
    633 

~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py in _call(self, method_name, request, response)
    148     while True:
    149       try:
--> 150         return self._call_method(method_name, request, response)
    151       except errors.AbortedError:
    152         num_retries -= 1

~/.cache/pypoetry/virtualenvs/mlmd-Ux9x4Ar2-py3.8/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py in _call_method(self, method_name, request, response)
    178         # description.
    179         # https://grpc.github.io/grpc/python/_modules/grpc.html#StatusCode
--> 180         raise _make_exception(e.details(), e.code().value[0])  # pytype: disable=attribute-error
    181 
    182   def _swig_call(self, method, request, response) -> None:

NotFoundError: No type found for query: MyArtifactType
```
with Pod's logs
```
2020-11-17 12:06:35.782095: W ml_metadata/metadata_store/metadata_store_service_impl.cc:79] GetArtifactType failed: No type found for query: MyArtifactType
```

**Comment by hughmiao** [comment]
@RafalSkolasinski in this deployment, what is the connection_config to the backend database passing to the server? If no physical database (e.g., mysql) config is given, then the server will simply use a in-memory fake store for each rpc request (see logging [1]), which explains the not_found error in the get type call. Please consider to pass a physical db flags like [2] or a config file [3]. The metadata_writer may be deprecated from KFP, IIUC. For the KFP deployment, consider open issues in https://github.com/kubeflow/pipelines for best practices/caveats of using the wrapper libs. 

/cc @dushyanthsc too for the kubeflow deployment flags guidelines, and the deprecation status of the metadata_writer.


[1] https://github.com/google/ml-metadata/blob/6688491b31175deca54996f827f3f07e2306be3c/ml_metadata/metadata_store/metadata_store_server_main.cc#L200

[2] https://github.com/google/ml-metadata/blob/6688491b31175deca54996f827f3f07e2306be3c/ml_metadata/metadata_store/metadata_store_server_main.cc#L157

[3] https://github.com/google/ml-metadata/blob/6688491b31175deca54996f827f3f07e2306be3c/ml_metadata/metadata_store/metadata_store_server_main.cc#L147

**Comment by RafalSkolasinski** [comment]
hmmm... so if I understand you right, the error is because of lack of mysql backend?

There's no more configuration then in the snippets above. I hoped to be able to indeed use for development the in memory fake database accepting that metadata will be persistent only as long as pod is alive. I do indeed have in logs:
```
2020-11-12 21:40:40.845536: W ml_metadata/metadata_store/metadata_store_server_main.cc:200] The connection_config is not given. Using in memory fake database, any metadata will not be persistent
```

**Comment by hughmiao** [comment]
>  the error is because of lack of mysql backend?

Yes. If mysql is a concern, you can also using a durable sqlite db as a backend. See the [config [3]](https://github.com/google/ml-metadata/blob/6688491b31175deca54996f827f3f07e2306be3c/ml_metadata/metadata_store/metadata_store_server_main.cc#L147) above and see the proto of that connection config [here](https://github.com/google/ml-metadata/blob/6688491b31175deca54996f827f3f07e2306be3c/ml_metadata/proto/metadata_store.proto#L560). Also some examples in the [get_started.md](https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#metadata-storage-backends-and-store-connection-configuration).

**Comment by RafalSkolasinski** [comment]
Finally had some time to look back into it. After creating a MySQL deployment and configuring `metadata_store_server` it seems to work properly. 

I still am puzzled a bit though why it didn't want to work with the fake in memory database. That seems like something handy in development so it'd be nice if it also worked in k8s.

**Comment by Bobgy** [comment]
Took me several hours to find this issue, same as @RafalSkolasinski, I'm looking for a setup that allows me to start a metadata_store_server for development purposes. I'm developing a go client of mlmd grpc server, so I cannot use the python in-memory fake DB.

> then the server will simply use a in-memory fake store for each rpc request (see logging [1])

the warning message was confusing, because I was exactly expecting an in-memory fake store. However, per observation when interacting with the DB, it seems to not persist anything at all (even in memory).

Is my understanding right that, each request creates a new fake in-memory store? therefore, different requests do not share the same instance and all data is lost? I'd hope that warning message can clarify that.

**Comment by Bobgy** [comment]
Figured out how to configure it with SQLite, this is convenient for local testing/development.

```
	docker run -it -p 8080:8080 \
		-v $$(pwd)/sqlite_connection_config:/config \
		--entrypoint /bin/metadata_store_server \
		gcr.io/tfx-oss-public/ml_metadata_store_server:0.25.1 \
		-metadata_store_server_config_file config
```

Content of `config` file:
```
connection_config{sqlite{filename_uri: "file:///mlmd.db"}}
```

it says use a file at `/mlmd.db` as file for SQLite.

With this approach, there's no need to start a separate mysql instance, we can just run this container and use it for testing/development.

**Comment by hughmiao** [comment]
@Bobgy , thanks! Just saw this. Yes, you can use a durable sqlite as a backend for dev. 

Good point to clarify this in the get_started doc, will close this after the doc is fixed.

**Comment by Bobgy** [comment]
@hughmiao tbh, I spent most of the time figure out the correct format for text proto config, not everyone is familiar with that, I think an example helps a lot in the documentation

**Comment by hughmiao** [comment]
@Bobgy good point. updated the doc and included an example. thanks for the suggestions.

**Comment by alokhom** [comment]
I have fixed it like this. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    app: mysql
data:
  init.sql: |
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      serviceAccountName: mysql
      containers:
      - args:
        - --datadir
        - /var/lib/mysql
        - --default-authentication-plugin=mysql_native_password
        - --disable-log-bin
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        # MLMD workloads (metadata-grpc-deployment and metadata-writer) depend on mysql_native_password authentication plugin. 
        # Mysql 8.0.26 supports the native auth with mysql_native_password
        image: gcr.io/ml-pipeline/mysql:8.0.26
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-preload-data-config

```
